### ISSUE TITLE
Stringhe impostazioni/prima installazione

### ISSUE THREAD

**Issue by chin8** [smartcommunitylab/sco.timetables#7]
Ridefinire le stringhe su categorie non vedenti/ vedenti in modo che un utente comprenda subito di cosa si sta parlando
Utilizzare le stringhe utilizzate nella schermata di installazione anche nella schermata delle impostazioni

**Comment by zaccog** [comment]
Io farei così:

Staccherei "Configura la app!" dal nome della app (così sembra parte del titolo e non cattura l'attenzione)

Scegli la modalità di visualizzazione della app (in seguito potrai modificare questa impostazione dal menù):

Per vedenti
Ottimizzata per utenti con diverse capacità visive.

Per ipovedenti e non-vedenti
Compatibile con supporti audiodescrittivi installati sul device (TalkBack / VoiceOver). Per attivarli, accedi alla sezione sezione "Accesso facilitato" nel menù del dispositivo.


Configure your app!

Select the app display mode (later, you will be able to change this setting from the menu):

Sighted
Optimized for users with different visual skills.

Visually impaired or blind
Compatible with descriptive audio tools installed on the device (TalkBack / VoiceOver). To activate them, go to the "Accessibility" section in the device menu.
